version: "3"

services:
  consul:
    image: consul
    container_name: consul
    ports:
      - "8500:8500"

  rabbitmq0:
    image: clevandowski/rabbitmq-autocluster:3.6.10
    hostname: rabbitmq0
    container_name: rabbitmq0
    environment:
      AUTOCLUSTER_TYPE: consul
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
      CONSUL_SERVICE_TTL: 60
      AUTOCLUSTER_CLEANUP: 'true'
      CLEANUP_WARN_ONLY: 'false'
      CONSUL_SVC_ADDR_AUTO: 'true'
    ports:
      - "5672:5672"
      - "15672:15672"

  rabbitmq1:
    image: clevandowski/rabbitmq-autocluster:3.6.10
    hostname: rabbitmq1
    container_name: rabbitmq1
    environment:
      AUTOCLUSTER_TYPE: consul
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
      CONSUL_SERVICE_TTL: 60
      AUTOCLUSTER_CLEANUP: 'true'
      CLEANUP_WARN_ONLY: 'false'
      CONSUL_SVC_ADDR_AUTO: 'true'
    ports:
      - "5673:5672"
      - "15673:15672"

  rabbitmq2:
    image: clevandowski/rabbitmq-autocluster:3.6.10
    hostname: rabbitmq2
    container_name: rabbitmq2
    environment:
      AUTOCLUSTER_TYPE: consul
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
      CONSUL_SERVICE_TTL: 60
      AUTOCLUSTER_CLEANUP: 'true'
      CLEANUP_WARN_ONLY: 'false'
      CONSUL_SVC_ADDR_AUTO: 'true'
    ports:
      - "5674:5672"
      - "15674:15672"
