---
- hosts: node1
  become: yes
  gather_facts: no
  tasks:
  - name: Define label rabbitmq on current node
    shell: docker node update --label-add rabbitmq="{{ item }}" "{{ item }}"
    with_items:
    - [ 'node1', 'node2', 'node3', 'node4' ]
